[BootPathType]
bootPath=OEMiROT
MCUBOOT_OVERWRITE_ONLY=0x1
[App]
APP_CODE_REGION_START=0x801A000
APP_CODE_REGION_SIZE=0xC6000
APP_DATA=0x1
APP_DATA_REGION_START=0x18000
APP_DATA_REGION_SIZE=0x2000
HEADER_SIZE=0x400
[Memory Region]
ROT_REGION_START=0x0
ROT_REGION_SIZE=0x18000
SCRATCH_REGION_START=0x18000
SCRATCH_REGION_SIZE=0x0
DOWNLOAD_ROT_REGION_START=0x0
DOWNLOAD_APP_CODE_REGION_START=0xE0000
DOWNLOAD_APP_DATA_REGION_START=0x1A6000
