[BootPathType]
bootPath=OEMiROT
MCUBOOT_OVERWRITE_ONLY=0x0
MCUBOOT_PRIMARY_ONLY=0x0
[App]
APP_CODE_REGION_START=0x802A000
APP_CODE_REGION_SIZE=0x16000
APP_DATA=0x1
APP_DATA_REGION_START=0x8028000
APP_DATA_REGION_SIZE=0x2000
HEADER_SIZE=0x400
[Loader]
LOADER_REGION_START=0x81F8000
LOADER_REGION_SIZE=0x8000
[Memory Region]
ROT_REGION_START=0x0
ROT_REGION_SIZE=0x18000
SCRATCH_REGION_START=0x8018000
SCRATCH_REGION_SIZE=0x10000
DOWNLOAD_ROT_REGION_START=0x0
DOWNLOAD_APP_CODE_REGION_START=0x8040000
DOWNLOAD_APP_DATA_REGION_START=0x8056000

