[BootPathType]
bootPath=OEMiROT
MCUBOOT_OVERWRITE_ONLY=0x0
[App]
APP_CODE_REGION_START=0x8032000
APP_CODE_REGION_SIZE=0xE6000
APP_DATA=0x1
APP_DATA_REGION_START=0x30000
APP_DATA_REGION_SIZE=0x2000
HEADER_SIZE=0x400
[Memory Region]
ROT_REGION_START=0x0
ROT_REGION_SIZE=0x18000
SCRATCH_REGION_START=0x18000
SCRATCH_REGION_SIZE=0x10000
DOWNLOAD_ROT_REGION_START=0x0
DOWNLOAD_APP_CODE_REGION_START=0x118000
DOWNLOAD_APP_DATA_REGION_START=0x1FE000
LOADER_REGION_START=0x8028000
LOADER_REGION_SIZE=0x8000
