[BootPathType]
bootPath=OEMiROT
MCUBOOT_OVERWRITE_ONLY=0x1
CMSE_VENEER_REGION_SIZE=0x400
CODE_IMAGE_ASSEMBLY=0x1
FLASH_SIZE=0x200000
[Secure]
S_CODE_REGION_START=0xC018000
S_CODE_REGION_SIZE=0x12000
HEADER_SIZE=0x400
[Memory Region]
ROT_REGION_START=0x0
ROT_REGION_SIZE=0x18000
SCRATCH_REGION_START=0x3C000
SCRATCH_REGION_SIZE=0x0
DOWNLOAD_S_CODE_REGION_START=0x2A000
