/*
 * Copyright (c) 2019, Arm Limited. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */
#include "region_defs.h"
#include "mcuboot_config/mcuboot_config.h"

#define _HEX(n) 0x##n
#define HEX(n)  _HEX(n)

/* Enumeration that is used by the assemble.py and imgtool\main.py scripts
 * for correct binary generation when nested macros are used
 */

enum image_attributes
{
  RE_FLASH_AREA_BL2_OFFSET = FLASH_AREA_BL2_OFFSET,
  RE_FLASH_AREA_BL2_SIZE = FLASH_AREA_BL2_SIZE,
  RE_FLASH_AREA_SCRATCH_OFFSET = FLASH_AREA_SCRATCH_OFFSET,
  RE_FLASH_AREA_SCRATCH_SIZE = FLASH_AREA_SCRATCH_SIZE,
/* area for preparing images */
  RE_IMAGE_FLASH_APP_IMAGE_SIZE = (APP_IMAGE_MAX_SIZE),
  RE_S_NS_PARTITION_SIZE = (APP_IMAGE_MAX_SIZE),
  RE_IMAGE_NON_SECURE_IMAGE_SIZE = (0x0),
  RE_IMAGE_FLASH_SECURE_IMAGE_SIZE = (APP_IMAGE_MAX_SIZE),
  
  RE_ADDRESS_APP_CODE_START = APP_CODE_START - BL2_HEADER_SIZE,
  
/* area for flashing images */
  RE_IMAGE_FLASH_ADDRESS_APP = (FLASH_BASE_ADDRESS+FLASH_AREA_0_OFFSET),
  RE_IMAGE_FLASH_ADDRESS_APP_MAGIC_INSTALL_REQ = (FLASH_BASE_ADDRESS+FLASH_AREA_0_OFFSET+FLASH_AREA_0_SIZE-0x10),
  RE_APP_IMAGE_NUMBER = (HEX(MCUBOOT_APP_IMAGE_NUMBER)),
  RE_S_DATA_IMAGE_NUMBER = (HEX(MCUBOOT_DATA_IMAGE_NUMBER)),
  RE_NS_DATA_IMAGE_NUMBER = (0x0),
  RE_EXTERNAL_FLASH_ENABLE = (0x0),

#if !defined(MCUBOOT_PRIMARY_ONLY)
  RE_IMAGE_FLASH_APP_UPDATE = (FLASH_BASE_ADDRESS+FLASH_AREA_2_OFFSET),
  RE_IMAGE_FLASH_APP_UPDATE_MAGIC_INSTALL_REQ = (FLASH_BASE_ADDRESS+FLASH_AREA_2_OFFSET+FLASH_AREA_2_SIZE-0x10),
  RE_PRIMARY_ONLY = (0x0),
#else
  RE_IMAGE_FLASH_APP_UPDATE = (FLASH_BASE_ADDRESS+FLASH_AREA_0_OFFSET),
  RE_IMAGE_FLASH_APP_UPDATE_MAGIC_INSTALL_REQ = (FLASH_BASE_ADDRESS+FLASH_AREA_0_OFFSET+FLASH_AREA_0_SIZE-0x10),
  RE_PRIMARY_ONLY = (0x1),
#endif /* MCUBOOT_PRIMARY_ONLY */

  RE_APP_DATA_IMAGE_NUMBER = ((MCUBOOT_DATA_IMAGE_NUMBER)),
#if (MCUBOOT_DATA_IMAGE_NUMBER == 1)
  RE_IMAGE_FLASH_ADDRESS_DATA = (FLASH_BASE_ADDRESS+FLASH_AREA_4_OFFSET),
  RE_IMAGE_FLASH_ADDRESS_DATA_MAGIC_INSTALL_REQ = (FLASH_BASE_ADDRESS+FLASH_AREA_4_OFFSET+FLASH_AREA_4_SIZE-0x10),
#if !defined(MCUBOOT_PRIMARY_ONLY)
  RE_IMAGE_FLASH_DATA_UPDATE = (FLASH_BASE_ADDRESS+FLASH_AREA_6_OFFSET),
  RE_IMAGE_FLASH_DATA_UPDATE_MAGIC_INSTALL_REQ = (FLASH_BASE_ADDRESS+FLASH_AREA_6_OFFSET+FLASH_AREA_6_SIZE-0x10),
#else
  RE_IMAGE_FLASH_DATA_UPDATE = (FLASH_BASE_ADDRESS+FLASH_AREA_4_OFFSET),
  RE_IMAGE_FLASH_DATA_UPDATE_MAGIC_INSTALL_REQ = (FLASH_BASE_ADDRESS+FLASH_AREA_4_OFFSET+FLASH_AREA_4_SIZE-0x10),
#endif /* MCUBOOT_PRIMARY_ONLY */
  RE_IMAGE_FLASH_DATA_IMAGE_SIZE = (FLASH_DATA_PARTITION_SIZE),
  RE_IMAGE_FLASH_SECURE_DATA_IMAGE_SIZE = (FLASH_DATA_PARTITION_SIZE),
  RE_IMAGE_FLASH_NON_SECURE_DATA_IMAGE_SIZE = (0x0),
#else
  RE_IMAGE_FLASH_ADDRESS_DATA = (0x0),
  RE_IMAGE_FLASH_ADDRESS_DATA_MAGIC_INSTALL_REQ = (0x0),
  RE_IMAGE_FLASH_DATA_UPDATE = (0x0),
  RE_IMAGE_FLASH_DATA_UPDATE_MAGIC_INSTALL_REQ = (0x0),
  RE_IMAGE_FLASH_DATA_IMAGE_SIZE = (0x0),
  RE_IMAGE_FLASH_SECURE_DATA_IMAGE_SIZE = (0x0),
  RE_IMAGE_FLASH_NON_SECURE_DATA_IMAGE_SIZE = (0x0),
#endif /* (MCUBOOT_S_DATA_IMAGE_NUMBER == 1) */

  /* Loader */
#if defined(MCUBOOT_EXT_LOADER)
  RE_LOADER_CODE_OFFSET = (FLASH_AREA_LOADER_OFFSET),
  RE_LOADER_CODE_START = (LOADER_CODE_START),
  RE_LOADER_CODE_SIZE = (LOADER_CODE_SIZE),
  RE_LOADER = 1,  
  RE_LOADER_WRP_START = (FLASH_AREA_LOADER_OFFSET),
  RE_LOADER_WRP_END = (FLASH_AREA_LOADER_OFFSET + LOADER_CODE_SIZE - 0x1),
#else
  RE_LOADER_CODE_OFFSET = (0x0),
  RE_LOADER_CODE_START = (0x0),
  RE_LOADER_CODE_SIZE = (0x0),
  RE_LOADER = 0,
  RE_LOADER_WRP_START = (0x1),
  RE_LOADER_WRP_END = (0x0),
#endif /* defined(MCUBOOT_EXT_LOADER) */
  
  RE_BL2_BOOT_ADDRESS = (BL2_BOOT_VTOR_ADDR),
  /* area for programming hardening on page */
  RE_BL2_WRP_START = (FLASH_AREA_BL2_OFFSET),

  RE_BL2_HDP_START = 0x0,
  RE_BL2_HDP_END = (FLASH_AREA_BL2_OFFSET+FLASH_AREA_BL2_SIZE+FLASH_AREA_SCRATCH_SIZE-0x1),
  RE_BL2_WRP_END = (FLASH_AREA_BL2_OFFSET+FLASH_AREA_BL2_SIZE-0x1),
  /* area for updates slot address */
  RE_AREA_0_OFFSET = FLASH_AREA_0_OFFSET,
  RE_AREA_0_SIZE = FLASH_AREA_0_SIZE,
  RE_AREA_2_OFFSET = FLASH_AREA_2_OFFSET,
  RE_AREA_2_SIZE = FLASH_AREA_2_SIZE,
  RE_AREA_4_OFFSET = FLASH_AREA_4_OFFSET,
  RE_AREA_4_SIZE = FLASH_AREA_4_SIZE,
  RE_AREA_6_OFFSET = FLASH_AREA_6_OFFSET,
  RE_AREA_6_SIZE = FLASH_AREA_6_SIZE,
  RE_APP_PARTITION_SIZE = FLASH_APP_PARTITION_SIZE,
  RE_FLASH_B_SIZE = FLASH_B_SIZE,

  RE_CRYPTO_SCHEME = CRYPTO_SCHEME,
#if defined(MCUBOOT_ENC_IMAGES)
  RE_ENCRYPTION = (0x1),
#else
  RE_ENCRYPTION = (0x0),
#endif
#if defined(MCUBOOT_OVERWRITE_ONLY)
  RE_OVER_WRITE = (0x1),
  RE_CMSE_VENEER_REGION_SIZE = (0x400),
#else
  RE_OVER_WRITE = (0x0),
  RE_CMSE_VENEER_REGION_SIZE = (0x2000),
#endif
#if (MCUBOOT_APP_IMAGE_NUMBER == 1) && (FLASH_NS_PARTITION_SIZE == 0)
  RE_OEMIROT_APPLI_FULL_SECURE = (0x1),
#else
  RE_OEMIROT_APPLI_FULL_SECURE = (0x0),
#endif
#if defined(DEVICE_1M_FLASH_ENABLE)
  RE_FLASH_SIZE = 0x100000,
#else
  RE_FLASH_SIZE = 0x200000,
#endif
  RE_OEMUROT_ENABLE = (0x0),
  RE_FLASH_PAGE_NBR = (0x7F)
};
